[package]
name = "odyssey-integration"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Integration tests for Odyssey Migrator (testcontainers)"
publish = false

[dev-dependencies]
odyssey-core = { workspace = true }
odyssey-cql = { workspace = true }
tokio = { workspace = true }
testcontainers = "0.23"
